#!/bin/bash
#xfr_serv="192.117.117.165"
#xfr_serv="192.117.235.231"
#xfr_serv="192.117.235.231" #xfr1 vip
#xfr_serv="ns1.bezeqint.net"
#xfr_serv="192.117.235.70" #nsy
#xfr_serv="192.114.75.70" #nsx
#xfr_serv="212.179.69.12" #nsa
#xfr_serv="212.179.61.180" #nsb
xfr_serv="212.25.69.218" #nsc
#xfr_serv="192.115.106.10" #current ns1

for zone in `cat /home/scripts/info/xfr_zones | awk '{print $1}'`
do
dig=`dig @$xfr_serv $zone | grep -i noerror`
if [ -z "$dig" ]
then
echo $zone: BAD
#dig @$xfr_serv $zone | grep -i fail
else
echo $zone GOOD
fi
done

